[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "ai.mssql"
version = "0.5.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["ai", "agent", "memory"]
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.mssql"

[platform.java21]
graalvmCompatible = true
